# Generated by Django 3.2.9 on 2026-07-15 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gave_money', models.IntegerField(default=0)),
                ('workers_money', models.IntegerField(default=0)),
                ('bugs_money', models.IntegerField(default=0)),
                ('code', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('currency', models.IntegerField(choices=[(1, 'UZS'), (2, 'USD'), (3, 'RUB')], default=1)),
                ('main', models.BooleanField(default=False)),
                ('mount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_mount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.IntegerField(choices=[(1, 'Haridor'), (2, 'Taminotchi'), (3, 'Turli shaxslar')])),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=830, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('trial', 'Sinov'), ('start', 'Start'), ('business', 'Biznes'), ('premium', 'Premium')], default='trial', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.DateTimeField(blank=True, null=True)),
                ('work_category', models.DateTimeField(blank=True, null=True)),
                ('cash', models.DateTimeField(blank=True, null=True)),
                ('product_category', models.DateTimeField(blank=True, null=True)),
                ('product_design', models.DateTimeField(blank=True, null=True)),
                ('storage', models.DateTimeField(blank=True, null=True)),
                ('outcome_category', models.DateTimeField(blank=True, null=True)),
                ('client', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.IntegerField(default=0)),
                ('sent_balance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_categories', to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='PIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DecimalField(decimal_places=1, max_digits=12)),
                ('start_mount', models.DecimalField(decimal_places=1, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis_items', to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DecimalField(decimal_places=1, max_digits=12)),
                ('status', models.IntegerField(choices=[(1, 'created'), (2, 'recieved'), (3, 'rejected')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_mount', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pis')),
            ],
        ),
        migrations.CreateModel(
            name='SavolJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=1500)),
                ('a', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('dona', 'dona'), ('metr', 'metr')], max_length=4)),
                ('deleted', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_categories', to='main.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
                ('got_balance', models.IntegerField(default=0)),
                ('bugs_sum', models.IntegerField(default=0)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile_images/')),
                ('birth', models.DateField(blank=True)),
                ('phone', models.PositiveIntegerField()),
                ('home_phone', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('code', models.BigIntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main.adminprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
                ('works', models.ManyToManyField(blank=True, related_name='category_workers', to='main.WorkCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
                ('length', models.FloatField(default=0)),
                ('sum', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='main.workcategory')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theworks', to='main.day')),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Sotish'), (2, 'Olish')])),
                ('finished', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('products', models.ManyToManyField(blank=True, to='main.ProductTurnover')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('type', models.IntegerField(choices=[(1, 'Hom ashyo'), (2, 'Yarim tayyor'), (3, 'Tayyor'), (4, 'Boshqa')])),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_designs', to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('type', models.IntegerField(choices=[(1, 'Hom ashyo'), (2, 'Yarim tayyor'), (3, 'Tayyor'), (4, 'Boshqa')])),
                ('m_type', models.IntegerField(choices=[(1, 'dona'), (2, 'metr'), (3, 'sm'), (4, 'tonna'), (5, 'kg'), (6, 'gram')])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.company')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productdesign')),
            ],
        ),
        migrations.AddField(
            model_name='pis',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis', to='main.product'),
        ),
        migrations.AddField(
            model_name='pis',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.storage'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('mount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.IntegerField(choices=[(1, 'UZS'), (2, 'USD'), (3, 'RUB')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Kirim'), (2, 'Chiqim'), (3, 'Harajat'), (4, 'Oylik')])),
                ('comment', models.TextField(default='Izoh yo`q')),
                ('client_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('for_product', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cash')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.outcomecategory')),
                ('client_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_cashs', to='main.cash')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.company')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.workerprofile'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='main.company'),
        ),
        migrations.AddField(
            model_name='cash',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashs', to='main.client'),
        ),
        migrations.AddField(
            model_name='cash',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashes', to='main.company'),
        ),
        migrations.CreateModel(
            name='BugWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=350)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='main.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('got_sum', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_payments', to='main.cash')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='main.workerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='main.company'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
